# Generated by Django 5.2 on 2025-04-24 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='user',
            field=models.ForeignKey(db_column='wx_openid', on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, to_field='wx_openid', verbose_name='关联用户'),
        ),
    ]
