"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import pymysql


pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# settings.py 添加活动media配置
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

MEDIA_URL = '/media/'  # URL 前缀（必须以斜杠开头和结尾）
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 本地文件存储路径
# 限制上传目录
ACTIVITY_IMAGE_UPLOAD_PATH = 'activity_images/'  # 会自动创建
TEMP_UPLOAD_DIR = 'temp_uploads/'
AVATAR_UPLOAD_DIR = 'avatars/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-euyuhn%@fhkt(bp#01affsf17)d-r71s2(x8udq@0@aquhx(&6'
# JWT认证环节配置
WEAPP_ID = 'wxb199f5280a879e1d'
WEAPP_SECRET = '67cc3f12fa469186c190649b32af759f'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['10.124.43.159',
                 '127.0.0.1',
                 'localhost',
                 '172.25.23.193',
                 '219.245.199.59',
                 'iecwxdk.nwafu.edu.cn'
                
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # 信任公网设备转发的HTTPS头

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 静态文件收集目录

CORS_ALLOW_ALL_ORIGINS = True

# Application definition
AUTH_USER_MODEL = 'login.User'
# 确保正确的应用顺序
INSTALLED_APPS = [
    # 基础应用
    'django.contrib.contenttypes',
    'django.contrib.auth',

    # 自定义用户模型应用（必须在auth之后）
    'login.apps.LoginConfig',
    'activities.apps.ActivitiesConfig',

    # 其他Django内置应用
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',

    # 第三方应用
    'corsheaders',
    'rest_framework',
    'channels',

    # 您的自定义应用
    'checkins.apps.CheckinsConfig',
    'broadcast',
]



# DRF配置
JWT_SECRET = '201126djc'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'myutils.JWTAuthentication',  # 启用自定义JWT认证
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # 全局默认需要认证
    ],
    'DEFAULT_RENDERER_CLASSES': [
            'rest_framework.renderers.JSONRenderer',  # 只返回JSON
    ]
}

# 跨域配置（如果前端单独部署）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # 前端开发地址
    "http://172.25.23.193:8000",  # 内网测试
    "https://your-production-domain.com"
]


# Channels配置
ASGI_APPLICATION = 'DjangoProject.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

# 注册信号处理器
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangotest',     # 数据库名
        'USER': 'root',            # 数据库用户名
        'PASSWORD': 'nwafu_yrl#610600',      # 数据库密码
        'HOST': 'localhost',       # 数据库地址
        'PORT': '3306',            # 端口
        'OPTIONS': {
            'charset': 'utf8mb4',  # 字符集
        }
    }
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

