# Generated by Django 4.2.20 on 2025-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=100, verbose_name='发布人')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('content', models.TextField(verbose_name='活动内容')),
                ('activity_time', models.DateTimeField(verbose_name='活动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
