# Generated by Django 5.2 on 2025-04-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='建议不超过50字', max_length=255, verbose_name='活动标题')),
                ('content', models.TextField(help_text='支持Markdown格式', verbose_name='活动详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('published_at', models.DateTimeField(blank=True, help_text='前端展示的时间（可预约未来发布）', null=True, verbose_name='发布时间')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location_name', models.CharField(help_text='如：教学楼A101', max_length=100, verbose_name='地点名称')),
                ('latitude', models.FloatField(blank=True, help_text='用于地图定位', null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('cover_image', models.ImageField(help_text='建议尺寸 16:9', upload_to='activity_covers/', verbose_name='封面图')),
                ('image_gallery', models.JSONField(default=list, help_text='存储图片URL数组', verbose_name='活动图集')),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='0表示不限人数', verbose_name='最大参与人数')),
                ('current_participants', models.PositiveIntegerField(default=0, editable=False, verbose_name='当前参与人数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('canceled', '已取消'), ('completed', '已结束')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('is_approved', models.BooleanField(default=False, help_text='管理员审核通过后才可见', verbose_name='审核状态')),
                ('creator', models.ForeignKey(help_text='活动创建者', on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动列表',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='activities__start_t_050f61_idx'), models.Index(fields=['status', 'published_at'], name='activities__status_d6914d_idx')],
            },
        ),
    ]
