# Generated by Django 5.2 on 2025-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('checkin', '打卡活动'), ('notification', '通知活动')], db_index=True, default='checkin', max_length=20, verbose_name='活动类型'),
        ),
    ]
