# Generated by Django 5.2 on 2025-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(help_text='建议尺寸 16:9', upload_to=models.ImageField(upload_to='', verbose_name='activity_images/'), verbose_name='封面图'),
        ),
    ]
